# Site settings
title: Aman Bhardwaj
description: A blog about Aman Bhardwaj
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aman Bhardwaj 
user_description: Bicycle HEKADALFLASD. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
#user_title: Software Developer
email: aman.b@outlook.com
twitter_username: itsamanbhardwaj
github_username:  itsamanbhardwaj
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
